//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSVrammed.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindowIsMaximized {
            get {
                return ((bool)(this["MainWindowIsMaximized"]));
            }
            set {
                this["MainWindowIsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle MainWindowBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["MainWindowBounds"]));
            }
            set {
                this["MainWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int VrammedMode {
            get {
                return ((int)(this["VrammedMode"]));
            }
            set {
                this["VrammedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowSplitterDstMain {
            get {
                return ((int)(this["MainWindowSplitterDstMain"]));
            }
            set {
                this["MainWindowSplitterDstMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowSplitterDstTexCmp {
            get {
                return ((int)(this["MainWindowSplitterDstTexCmp"]));
            }
            set {
                this["MainWindowSplitterDstTexCmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowSplitterDstPalEdt {
            get {
                return ((int)(this["MainWindowSplitterDstPalEdt"]));
            }
            set {
                this["MainWindowSplitterDstPalEdt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color TextureMarkerColor {
            get {
                return ((global::System.Drawing.Color)(this["TextureMarkerColor"]));
            }
            set {
                this["TextureMarkerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color CompareMarkerColor {
            get {
                return ((global::System.Drawing.Color)(this["CompareMarkerColor"]));
            }
            set {
                this["CompareMarkerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color PaletteMarkerColor {
            get {
                return ((global::System.Drawing.Color)(this["PaletteMarkerColor"]));
            }
            set {
                this["PaletteMarkerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color CompareResultColor {
            get {
                return ((global::System.Drawing.Color)(this["CompareResultColor"]));
            }
            set {
                this["CompareResultColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public float CompareResultAlpha {
            get {
                return ((float)(this["CompareResultAlpha"]));
            }
            set {
                this["CompareResultAlpha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TextureMarkerLocation {
            get {
                return ((global::System.Drawing.Point)(this["TextureMarkerLocation"]));
            }
            set {
                this["TextureMarkerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size TextureMarkerSize {
            get {
                return ((global::System.Drawing.Size)(this["TextureMarkerSize"]));
            }
            set {
                this["TextureMarkerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CompareMarkerLocation {
            get {
                return ((global::System.Drawing.Point)(this["CompareMarkerLocation"]));
            }
            set {
                this["CompareMarkerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PaletteMarkerLocation {
            get {
                return ((global::System.Drawing.Point)(this["PaletteMarkerLocation"]));
            }
            set {
                this["PaletteMarkerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot1 {
            get {
                return ((string)(this["EditFileSlot1"]));
            }
            set {
                this["EditFileSlot1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot2 {
            get {
                return ((string)(this["EditFileSlot2"]));
            }
            set {
                this["EditFileSlot2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot3 {
            get {
                return ((string)(this["EditFileSlot3"]));
            }
            set {
                this["EditFileSlot3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot4 {
            get {
                return ((string)(this["EditFileSlot4"]));
            }
            set {
                this["EditFileSlot4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot5 {
            get {
                return ((string)(this["EditFileSlot5"]));
            }
            set {
                this["EditFileSlot5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot6 {
            get {
                return ((string)(this["EditFileSlot6"]));
            }
            set {
                this["EditFileSlot6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot7 {
            get {
                return ((string)(this["EditFileSlot7"]));
            }
            set {
                this["EditFileSlot7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot8 {
            get {
                return ((string)(this["EditFileSlot8"]));
            }
            set {
                this["EditFileSlot8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot9 {
            get {
                return ((string)(this["EditFileSlot9"]));
            }
            set {
                this["EditFileSlot9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EditFileSlot10 {
            get {
                return ((string)(this["EditFileSlot10"]));
            }
            set {
                this["EditFileSlot10"] = value;
            }
        }
    }
}
